### ISSUE TITLE
Аутентификация

### ISSUE THREAD

**Issue by baio** [tradernet/tn.api#1]
Привет, отличный интерфейс!

Не хватает документации, по авторизации,  пожайлуста добаьте. Или напишите рутину как авторизироваться для выставления заявок здесь. По текущей докуметнации авторизации не могу разобраться.

Через браузер залогинется получилось но только после того как прошел авторизацию через сайт, а интересует имено аутенифекация через node.

Спасибо.

**Comment by tradernet** [comment]
Привет!
Да, в API сейчас реализована авторизация для браузера. Для сервера добавим в течение одной-двух недель.

Спасибо за то, что обратили внимание на этот пробел :)

**Comment by baio** [comment]
спасибо, жду с нетерпением. еще пожелание - рассмотриет возможность добавления к API сообщений silver surfer .

**Comment by tradernet** [comment]
Привет! Добавили авторизацию по ключу. 
Пока работает только на wsbeta для демо-клиентов. Можете пробовать. 
https://github.com/tradernet/tn.api#%D0%9F%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8%D0%B7-nodejs-%D0%B1%D0%B5%D0%B7-%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80%D0%B0
Silver surfer, возможно, добавим, но не в ближайшее время.

**Comment by baio** [comment]
Спасибо! Обязательно попробую в ближайшее время.

2015-03-11 13:36 GMT+04:00 tradernet notifications@github.com:

> Привет! Добавили авторизацию по ключу.
> Пока работает только на wsbeta для демо-клиентов. Можете пробовать.
> 
> https://github.com/tradernet/tn.api#%D0%9F%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8%D0%B7-nodejs-%D0%B1%D0%B5%D0%B7-%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80%D0%B0
> Silver surfer, возможно, добавим, но не в ближайшее время.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tradernet/tn.api/issues/1#issuecomment-78231118.

## 

---

С уважением

Путилов Максим Александрович

**Comment by baio** [comment]
привет! что то не срослось пока пишет

WS connect
Ошибка авторизации { message: 'Bad sign.' }

---

node -v
v0.10.33

тут код с ключами (потом перегенрю)

var io = require('socket.io-client');
var tncrypto = require('./tn-crypt');

var pubKey = 'd60d46b0442b692ffcd881ea440187ff';
var secKey = '438e2c862ba32a13233fc7dd7d8e15ad043656ea';

var ws = io('https://wsbeta.tradernet.ru', {
    transports: ['websocket']
});

ws.on('connect', function () {
    console.log('WS connect');
    auth(ws, pubKey, secKey, function (err, auth) {
        if (err) return console.error('Ошибка авторизации', err);
        console.log('login:', auth.login);
        console.log('mode:', auth.mode);
        if (auth.trade)
            console.log('Приказы подавать можно');
        else
            console.log('Приказы подавать нельзя');
    });
});

function auth(ws, pubKey, secKey, cb) {
    var data = {
        apiKey: pubKey,
        cmd: 'getAuthInfo',
        nonce: Date.now()
    };
    var sig = tncrypto.sign(data, secKey);
    ws.emit('auth', data, sig, cb);
}

2015-03-11 14:10 GMT+03:00 Max Max max.putilov@gmail.com:

> Спасибо! Обязательно попробую в ближайшее время.
> 
> 2015-03-11 13:36 GMT+04:00 tradernet notifications@github.com:
> 
> > Привет! Добавили авторизацию по ключу.
> > Пока работает только на wsbeta для демо-клиентов. Можете пробовать.
> > 
> > https://github.com/tradernet/tn.api#%D0%9F%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8%D0%B7-nodejs-%D0%B1%D0%B5%D0%B7-%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80%D0%B0
> > Silver surfer, возможно, добавим, но не в ближайшее время.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/tradernet/tn.api/issues/1#issuecomment-78231118.
> 
> ## 
> 
> ---
> 
> С уважением
> 
> Путилов Максим Александрович

## 

---

С уважением

Путилов Максим Александрович

**Comment by papagenoo** [comment]
Привет!
Да, всё верно. Вы сгенерировали ключи на боевом сайте, а используете на бете. 
Сгенерируйте их на https://beta.tradernet.ru
На боевом пока этот функционал не работает.

**Comment by baio** [comment]
упс, спасибо

2015-03-12 12:45 GMT+04:00 papagenoo notifications@github.com:

> Привет!
> Да, всё верно. Вы сгенерировали ключи на боевом сайте, а используете на
> бете.
> Сгенерируйте их на beta.tradernet.ru
> На боевом пока этот функционал не работает.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tradernet/tn.api/issues/1#issuecomment-78442037.

## 

---

С уважением

Путилов Максим Александрович

**Comment by baio** [comment]
Все работает супер!
Когда ждать в рабочей версии ?

**Comment by baio** [comment]
Здраствуйте, подскажите, появилась ли авторизация на рабочем сервере?

**Comment by chip-and-dail** [comment]
Есть новости? С марта тишина.

**Comment by baio** [comment]
@chip-and-dail  они запустили боевую версию на прошлой неделе можно пользоваться

**Comment by chip-and-dail** [comment]
@baio Вопрос как. Если правильно понимаю, решение построено на работу с сокетами. Хотелось бы узнать на тему работы с сервера, без js.

**Comment by baio** [comment]
здесь есть примеры использования (смотри в экзамплах и тестах) https://github.com/data-avail/trader-net

Использовать можно на ndejs, все тоже самое что и в клиентских версиях, единственное различие в аунтентификации, пример серверной можно посмотреть в экзамлах этого репозитория.

**Comment by chip-and-dail** [comment]
Стало хуже. Я перестал что-либо понимать :) Пишу на java, php, ruby, может поэтому совсем не понимаю, чего тут делают скрипты? 

Разве не будет работать с обычными HTTP-запросами?

**Comment by baio** [comment]
Библиотеки до работы с веб сокетами есть во всех языках, поэтому тебе нужно адаптировать примеры на язык который хочешь использовать, или использовать нод в этом случае ничего адаптировать не нужно )

**Comment by chip-and-dail** [comment]
Гемор какой-то, а не API. Было старое, работающее, а теперь не пойми что. Хотелось бы получить официальный ответ.

**Comment by baio** [comment]
лучшее враг хорошего ;) на самом все работает. Я так понимаю они апи под себя делают, опенсорсят то что используют в своем веб клиенте. А то что фидбэка никакого нет это да проблема.

**Comment by chip-and-dail** [comment]
@baio Нужно бы ещё попробовать написать в поддержку, которая на nettrader.

**Comment by baio** [comment]
У меня есть кантакт через менеджера, но это конечно не удобно. Весь апи для работы есть и он удобен, только нужно научится использовать веб сокеты, там на самом деле ничего сложного.

![omg](http://blog.circleci.com/wp-content/uploads/2015/06/With-It.png)

**Comment by chip-and-dail** [comment]
Веб-сокеты хороши, когда нужно показывать котировки в realtime. Но если этого не нужно, а нужны исторические данные или данные по портфелю или типа того - то сокеты схожи с ездой на авто от до соседнего подъезда. Задача простая, а гемора - полно.

**Comment by Dmatafonov** [comment]
> Гемор какой-то, а не API. Было старое, работающее, а теперь не пойми что. Хотелось бы получить официальный ответ.

Нужен resfull API для торговли?

**Comment by chip-and-dail** [comment]
@Dmatafonov А о торговли речи не ведётся. Нужны данные и не обязательно в режиме realtime. Т.е. да, для торговли, для того, чтобы показывать котировки прямо сейчас - существующий способ может и хорош. Но зачем усложнять, когда требуется получить к примеру:
- список всех бумаг в портфеле
- исторические данные по бумаге
- котировки например часовой давности

Yahoo примерно так и делает. В плане бумаг. Информацию по бумаге можно получить одним буквально запросом и не важно откуда он сделан. Там система посложнее (в том плане, что у них подобие базы данных и отправляешь не только get-запрос, но и подобие sql-запроса), но всё же данные получаются в одну строку.

В старом API-в целом, всё нужное есть. И оно даже местами работает (наверное только кроме авторизации). Но никто ведь не сообщает насколько долго оно всё так будет работать (якобы планируется закрывать), а значит приходится обращаться к текущему API и строить новую архитектуру.

Кстати. Дополнительный вопрос. Где можно прочитать про условия использования API? Не нашёл подобной информации. Например, если проект открытый, то нужно ли сообщать - откуда берутся данные?

**Comment by Dmatafonov** [comment]
Котировки распространять не имеете права, биржа может заметить и отругать. Мы их предоставляем только для личного non-display использования.

Аналог старого API по http запрос-ответ сделаем.
Старое XML API работает, на нем в частности крутится Iphone приложение. Но не разрабатывается дальше и там много чего нет из нового - все что добавлялось последние три года там отсутствует.

**Comment by chip-and-dail** [comment]
Имеете ввиду исторические данные котировок или в реальном времени?

Ну из-за меня конечно делать не обязательно :) Я всё же попробую поработать с текущим API. Может и получится чего.

В любом случае, спасибо что ответили на вопросы.
