### ISSUE TITLE
проверять поле userOrderId при исполнении сделок

### ISSUE THREAD

**Issue by baio** [tradernet/tn.api#10]
При выставлении сдлеки необходимо контролировать, была ли сделка уже выставлена юзером по полю userOrderId и соответственно сделать это поле стринговым, если пользователь пытается выставить сделку с тем же userOrderId, то возвращать ошибку, без этого в распределенных системах никак. Конечно это все можно пытаться контролировать в коде, но это усложняет имплементацию клиента и в любом случае не гарантирует задвоение сделок.

**Comment by baio** [comment]
плюс сюдаже, было бы супер удобно иметь userOrderId типа string а не number

**Comment by Dmatafonov** [comment]
это текстовое поле которое пользователь использует как хочет - оно для пользователя и сделано

соответственно накладывать на него ограничения уникальности или типа - противоречит условию "использует как хочет"

на разных биржах реализовано по разному - но везде подобное поле служит для обратной связи с базами данных самого пользователя. бирже (нам в данном случае) пофигу что вы туда пишете - это для вашего же удобства отслеживания результатов исполнения приказов или маркировки позиций

в приказе можно отправить кроме userOrderId еще и order_name - оно придет потом и в позиции

например часть приказов отправляете с признаком "spec", часть приказов в с признаком "invest"  - в итоге будет видно в позициях к какому портфелю та или иная позиция относится

**Comment by baio** [comment]
:thumbsup: и пожелание, почаще выходите на связь здесь

**Comment by Dmatafonov** [comment]
dmatafonov скайп если есть вопрос всегда свяжу с кем то из разработчиков
