### ISSUE TITLE
А что с API, которое на nettrader?

### ISSUE THREAD

**Issue by chip-and-dail** [tradernet/tn.api#13]
У вас есть API, которое лежит на http://www.nettrader.ru/guide/onthetrading/overview Есть также здесь. То было удобно для серверной работы, но теперь говорят, что оно не актуально. А тут везде JavaScript. Чего делать-то? Каким пользоваться?

**Comment by baio** [comment]
в папке example есть примеры

**Comment by chip-and-dail** [comment]
Там JS

**Comment by chip-and-dail** [comment]
@baio там JS

**Comment by Dmatafonov** [comment]
Пользоваться через установку на сервер nodeJs.

Штука крайне элементарная, работает быстро, коннект держит постоянный.

Преимуществ перед http просто куча - во первых авторизация только при открытии коннект, во вторых обновления получаются не циклическими запросами, а по мере их появления.

Для торгового робота соединение по restfull api это просто капец как неудобно - просто чтобы узнать что котировка изменилась - нужно отдельный запрос посылать. То же самое со статусом приказов, с портфелем.

При работе с nodejs все обновления сыпятся сразу по мере их появления. JS проще любого серверного языка известного мне.

Мы конечно сделаем возможность и restfull api - но это крайне неэффективно, очень рекоменду все таки поставить nodejs и написать под него сервер. Я с нуля в нем разобрался за день - там все максимально примитивно.

**Comment by chip-and-dail** [comment]
Уговорили, посмотрим что это такое. Просто архитектура усложняется таким образом. Т.е. для какого-то продукта самый простой вариант - это отправлять HTTP-запросы и получать ответы. Сделал GET - получил что-то. Сделал POST - отправил что-то. А тут получается нужно делать какие-то надстройки..

**Comment by ghost** [comment]
Кстати, а я POST запросами с Nettrader API работаю. Написал для себя классец на PHP.
Вот скриншот начала класса: https://pp.vk.me/c628530/v628530752/1c026/bslZj7UJ588.jpg
Если инетересно, можно обсудить в скайпе: pro_co_ru (я не работаю в неттрейдер, просто мимо проходил :)
