### ISSUE TITLE
Старый Http API все еще работает или отключили?

### ISSUE THREAD

**Issue by AlFrolov** [tradernet/tn.api#18]
Доступен ли для использования старый API (который через GET и POST http запросы)? Если работает, то будет он работать в дальнейшем или нет? Какие планы?

**Comment by Dmatafonov** [comment]
работает

развиваться не будет - будет отдельный rest api в json формате

**Comment by AlFrolov** [comment]
Как я понял, старый API отключили. Теперь нужно пользоваться новым REST API? В описалове к нему не нашел как подавать приказы? Или эта возможность еще не реализована?

**Comment by Dmatafonov** [comment]
Старый не отключали, но лучше не юзать. Не поддерживаем.

Новый забыли описать. Упс. Сделаем.

**Comment by ilyacherevkov** [comment]
Описали?

Что-то непонятно, данные тут https://github.com/tradernet/tn.api и тут  https://tradernet.ru/tradernet-api/orders-get-current-history отличаются сильно (по REST). что юзать? Пример для питона использует старый или новый API?

**Comment by ilyacherevkov** [comment]
Что-то непонятно, данные тут и тут  https://tradernet.ru/tradernet-api/orders-get-current-history отличаются сильно

**Comment by Dmatafonov** [comment]
Питон на новом.

> тут https://github.com/tradernet/tn.api

Это старое API - часть методов и в новом также работает, часть не будет работать вообще. Части методов в старом нету.

**Comment by ilyacherevkov** [comment]
Спасибо!
