### ISSUE TITLE
Клиент на Ruby

### ISSUE THREAD

**Issue by ilyacherevkov** [tradernet/tn.api#19]
1. **REST клиент Ruby**

C рождеством! Помогите, пожалуйста, я пишу клиент на ruby под REST.  
При отправке команды, требующей аутентификации, от сервера приходит ответ 
`{"code"=>15, "errMsg"=>"Bad nonce."}` При этом, заявки и позиции успешно открываются и видны в веб-интерфейсе.
Вот [ссылка на Gist ](https://gist.github.com/ilyacherevkov/61d9b03c2c2880974f78c8838079d6b7) 

Nonce всегда возрастающий, генерируется примерно как в примере на python, длина такая же. Подпись в python и в ruby  получается идентичной при подставлении одинакового nonce.
Клиент нужен для того, чтобы запустить бота. Это не HFT, максимум 2 сделки в день, поэтому достаточно REST вполне.

2. **Есть ли REST интерфейс (v2) для получения стакана, а также OHLC / HLOC?**

В примерах не нашел - только socket.

**P.S.** Пример на PHP, скачанный сайта, мне возвращает `{"code":4,"errMsg":"Bad sign."}`
**P.S. 2**  Для ws тоже пытался написать клиент, но не понял пока где актуальная документация по аутентификации через API ключи. ситуация похожа на [#16](https://github.com/tradernet/tn.api/issues/16). Вот [ссылка на Gist](https://gist.github.com/ilyacherevkov/7873017f8152b3d0e24f5b8e345b1ab1) с наработками по ws - работает только получение котировок и т.п. Выставление ордеров - нет.

**Comment by ilyacherevkov** [comment]
С вопросом 1 разобрался - поменял HTTP клиент с Curb на Rest-client - заработало (см [Gist](https://gist.github.com/ilyacherevkov/61d9b03c2c2880974f78c8838079d6b7)).  Остался вопрос 2.

**Comment by ilyacherevkov** [comment]
С OHLC  тоже разобрался - остался стакан.

**Comment by Dmatafonov** [comment]
Стакан шлет столько данных что для него REST и не планируется. Задосите нас.

**Comment by Dmatafonov** [comment]
Свечки по ресту можно получить. Обычный get запрос. Пример тут:
http://jsbin.com/fifufukibu/1/edit?html,js,output

**Comment by ilyacherevkov** [comment]
Спасибо, по OHLC понял, получение работает, добавил в клиент (правда работает через post у меня только).

Хотел получить дневные свечки по  BRG7.  Почему-то колоссальная разница между некоторыми днями данных самой биржи и ответа сервера http://moex.com/ru/derivatives/contractresults.aspx?code=BR-2.17 - иногда больше 2 долларов, иногда совпадает более менее. В поддержке сказали это из-за тестового сервера, а также, что в целом данные будут различаться т.к. NetTrader формирует сам свой HLOC.  Но вроде запрос идет на обычный url + там нет нигде подписи - т.е. это не тестовый сервер. И разница до 2.5$ с биржей смущает. Использовал такие параметры при запросе.

var exampleParams = {
   securityId: 42776,
   id: 'BRG7',
   count: -1,
   timeframe: 1440,
   date_from: '18.08.2016 00:00',
   date_to: '08.01.2017 00:00',
   interval: 'D1',
   intervalMode: 'ClosedRay',
   demo: 0
};

**Comment by Dmatafonov** [comment]
на бирже торговый день заканчивается в 19, когда начинается вечерний клиринг

не проверял что они на сайте выкладывают, но думаю у них и данные за торговый день именно по этот временной интервал

У нас торговый день и свеча формируются по календарю, то есть в нее попадает еще и вечерняя сессия - до 12 ночи по Мск. Так что разница может быть существенной.

**Comment by ilyacherevkov** [comment]
Да, вроде так и есть.

**Comment by ilyacherevkov** [comment]
В поддержке МосБиржи сказали, что данные за весь день с утра до 12 ночи. Но они не совпадают не только с неттрейдером, но и с Финамом и прочими брокерами, при этом данные брокеров практически идентичны между собой. Там разница 2 доллара и больше по фьючерсу нефти - ужас какой-то, это же не 10 центов

**Comment by Dmatafonov** [comment]
хбз, у нас все просто - что биржа присылает, то и попадает в свечи

а что они у себя на сайте выкладывают - только они и знают
может туда еще итоги аукционов записываются (хотя какие аукционы на фортсе), может среднезвес закрытия считают как то хитро - не знаю, но я бы им не доверял )

**Comment by ilyacherevkov** [comment]
Разобрался - открытие свечи на 19:05, закрытие на 18:45 след. дня на сайте мосбиржи (итоги торгов), что конечно не совпадает с обычными дневными свечками

**Comment by Dmatafonov** [comment]
так и думал что в поддержке биржи просто не в курсе

у них ночная сессия приклеена к следующему дню, поэтому их свечки погоду показывают
