### ISSUE TITLE
Выставление заявок на Украинской бирже

### ISSUE THREAD

**Issue by derand** [tradernet/tn.api#2]
Добрый день.

Никак не получается выставить ордер на УБ, на страничке профайла показывается, что деньги на счету есть,  а при выставлении ордера на https://tradernet.ru/terminal — недостаточно денег.

**Comment by TradernetAdmin** [comment]
Добрый день.

Можете дать больше подробностей когда пробовали выставлять, какой ответ пришел, вернулся ли в ответ номер приказа и какой?

**Comment by derand** [comment]
Добрый день.

Пробую выставлять на страничке веб-терминала – https://tradernet.ru/terminal. Нажимаю кнопку "Получить СМС код", ввожу его, система показывает форму ввода параметров заявки, но количество лотов изменить с нуля нельзя. Пишет: "Недостаточно денег на счету".

Кстате, сейчас когда захожу в свой профайл https://tradernet.ru/user/Andrіy, на месте где раньше писалось кол-во денег на счету сейчас стоит прочерк. Хотя когда открывал тикет, там деньги отображались.

Теперь если я пытаюсь выставить заявку с помощью API:
Первое, я проверяю есть ли открытая сессия безопасности, если нет, то делаю её запрос на открытие с помощью получение токена через СМС и ввожу в "**openSecuritySession**".
После пытаюсь выставить ордер, послав сообщение по _websocket_:

```
["putOrder", {"expiration_id": 1, "aon": 0, "submit_ch_c": 1, "qty": 1, "limit_price": 1050, "curr": "RUR", "userOrderId": 123, "groupPortfolioName": 12, "order_type_id": 2, "instr_name": "UXH5", "message_id": 0, "action_id": 1}]
```

на что получаю ответ:

```
[null,{"orderId":8172198,"userOrderId":123}]
```

т.е. ордер выставляется.

Если я в этот момент подписан на получение приказов клиента, то мне приходит сообщение:

```
["orders",[{"orders":{"order":[{"aon":0,"cur":"UAH","date":"2015-03-12T17:31:10.987","exp":1,"fv":100,"id":8172198,"instr":"UXH5","name":"UX-3.15","name2":"UX-3.15","oper":1,"p":1050,"q":1,"rep":0,"stat":70,"stat_d":"2015-03-12T17:31:10.997","stat_orig":1,"stop":0,"stop_activated":1,"type":2,"@text":"Приказ не может быть принят, так как выбранная РПС не допускает подачу приказов по данному инструменту.","trade":[],"stat_prev":null,"userOrderId":null}]}}]]
```

тестировалось во время работы биржы.

**Comment by TradernetAdmin** [comment]
По второй части. "...выбранная РПС не допускает подачу приказов..." - это сообщение возникает из-за того, что на текущий момент срочный рынок украинской биржи не доступен в торговой системе TRADERNET. Можно торговать только на споте.

По первой части. Вопрос относится к работе терминала и обеспечению, доступному в портфеле. Такие вопросы мы решаем только подтвердив, что Вы тот клиент, о ком говорите. Предлагаю с этим вопросом обратиться через клиентский отдел. Сразу скажу, что понадобится скриншот выставления заявки и номер приказа, который не принялся, если он создался в момент подачи. Здесь желательно обсуждать только работу API.

**Comment by derand** [comment]
Ясно, спасибо, тогда, наверно, тикет можно закрыть. Хотя хотелось бы иметь возможность торговать на срочном рынке УБ.
