### ISSUE TITLE
Как получить данные по индексам?

### ISSUE THREAD

**Issue by no-cat-no** [tradernet/tn.api#20]
У МосБиржи есть разные индексы, как основные, так и отраслевые и тематические (http://moex.com/ru/indices). Скажите, как получить по ним данные? Т.е. MICEXINDEXCF и RTSI есть, а вот например второй эшелон никак: https://tradernet.ru/api/?q[cmd]=getQuotesHistory&q[params][ticker]=MICEXSC&q[params][interval]=D&q[params][from]=2015-5-31&q[params][to]=2016-5-08

**Comment by Dmatafonov** [comment]
отраслевые не заводили - никому никогда не были нужны :)
