### ISSUE TITLE
Как найти ФосАгро?

### ISSUE THREAD

**Issue by no-cat-no** [tradernet/tn.api#21]
На сайте МосБиржи у ФосАгро код **PHOR** (http://moex.com/ru/listing/securities-cards.aspx?id=4161). Пробую его в запросе - пусто:
https://tradernet.ru/api/?q[cmd]=getQuotesHistory&q[params][ticker]=PHOR&q[params][interval]=D&q[params][from]=2015-5-31&q[params][to]=2016-5-08 Как его найти? Пробовал по ISIN - тоже самое.

**Comment by Dmatafonov** [comment]
Тикеры в ТН не всегда совпадают с тикерами биржи. Так что сначала нужно смотреть тикер правильный методом поиска (или просто руками в терминале набрать и посмотреть какой тикер) и лишь затем пытаться получить данные. С Мосбиржей очень редко тикеры не совпадают, а вот на других биржах несовпадений больше, так что проверяйте.

Корректный тикер фосагро в трейдернете RU000A0JRTA9

https://tradernet.ru/api/?q%5Bcmd%5D=getQuotesHistory&q%5Bparams%5D%5Bticker%5D=RU000A0JRTA9&q%5Bparams%5D%5Binterval%5D=D&q%5Bparams%5D%5Bfrom%5D=2015-5-31&q%5Bparams%5D%5Bto%5D=2016-5-08

**Comment by no-cat-no** [comment]
А с чем связаны несовпадения?
И есть ли где-то опубликованный список ваших тикеров с названиями компаний, чтобы можно было провести визуальное сравнение, а не проверять каждую бумагу?

Спасибо

**Comment by Dmatafonov** [comment]
Биржа меняет тикеры - а мы нет. Поэтому и несовпадения.

https://tradernet.ru/stocks/securities/get-list

**Comment by no-cat-no** [comment]
Т.е. можно сказать что у вас исходные названия бумаг.. Понятно, спасибо большое.
