### ISSUE TITLE
Как получить курс валют?

### ISSUE THREAD

**Issue by no-cat-no** [tradernet/tn.api#22]
В прошло issue вы указали список https://tradernet.ru/stocks/securities/get-list Там есть EUR/RUB и какой-то EURRUB_RSK. 
Скажите, что такое EURRUB_RSK и как правильно получить курс eur/rub например?

**Comment by Dmatafonov** [comment]
'EUR/RUB' - это корректная пара

'EURRUB_RSK' - хз что такое, нам тоже много дряни с биржи прилетает (очень много) так что мы далеко не все инструменты знаем/используем

**Comment by no-cat-no** [comment]
Хорошо, а как тогда EUR/RUB получить?

https://tradernet.ru/api/?q[cmd]=getQuotesHistory&q[params][ticker]='EUR/RUB'&q[params][interval]=W&q[params][from]=2016-10-01&q[params][to]=2016-10-02

Варианты 'EUR/RUB', EUR_RUB не подходят

**Comment by Dmatafonov** [comment]
сорри - EUR/RUR это не инструмент (такого на бирже нет), это просто текущий курс ЦБ, для него нет свечей (как и для остальных валютных пар)

чтобы получить некую историю курса, нужно запрашивать например историю по фьючерсу валютному

например вот доллар/рубль 

https://tradernet.ru/api/?q[cmd]=getQuotesHistory&q[params][ticker]=SIH7&q[params][interval]=W&q[params][from]=2016-10-01

или евро/рубль

https://tradernet.ru/api/?q[cmd]=getQuotesHistory&q[params][ticker]=EUH7&q[params][interval]=W&q[params][from]=2016-10-01

если нужна именно история курсов валют, то сайт ЦБ в помощь - они ее ведут

**Comment by Dmatafonov** [comment]
но мысль создать синтетический инструмент и сохранить туда курсы я уловил
сделаем

**Comment by no-cat-no** [comment]
Да, потому и удивился. А фьючерсы придётся склеивать...

**Comment by no-cat-no** [comment]
Спасибо за помощь, пока вопросы кончились :)

**Comment by ilyacherevkov** [comment]
Лучше руками склеить фьючерсы самому и быть 100% уверенным в методологии склейки - финам , например, непонятно как склеивает, что сильно влияет а результаты бэктэстов из-за неожиданных гэпов. А курс  ЦБ можно по API цб получать

**Comment by no-cat-no** [comment]
@ilyacherevkov Курс у ЦБ получать не очень, потому что он от ЦБ и сильно отходит от банковских и биржевого. 

А вот склеивать фьючерсы - вопрос спорный, потому что нужно тогда знать, какой фью следующий, т.е. его номер, даты и т.д. Ну ладно, номер считается, но даты ж разные вроде...

**Comment by ilyacherevkov** [comment]
@no-cat-no так по API NetTrader можно получить даты экспирации любого фьючерса (либо по открытому API мосбиржи, но там иногда некорректные - столкнулся). Я за пару часов написал скрипт склейки. Ресурс mfd склеивает по экспирации, там можно скачать. Не уверен, что там есть валютные фьючерсы

**Comment by Dmatafonov** [comment]
> Ресурс mfd склеивает по экспирации, там можно скачать. Не уверен, что там есть валютные фьючерсы


склеивать нужно сильно с умом - фьючерсы одновременно торгуются и старый и новый какое то время, причем в это время у них сильно разные цены

по идее нужно всегда брать цену ближайшего фьючерса, она наиболее близка к средневзвесу

но с другой стороны курс ЦБ совсем не плох - по сути это средневзвес биржевого курса, так что если нужно просто пересчитать например из одной валюты в другую, то не нужно мучать фьючерсы, ЦБ более чем достаточно и он будет точнее

фьючи нужны когда вы собираетесь именно валютный арбитраж делать, то есть торговать именно этими фьючерсами - в остальных случаях от них больше проблем чем толку
