### ISSUE TITLE
Rest API отправка приказов, получение котировок

### ISSUE THREAD

**Issue by AlFrolov** [tradernet/tn.api#23]
День добрый,

Новый REST API содержит функционал по отправке приказов/получению котировок? А то в описалове только возможность получения новостей, постов и прочего...

**Comment by Dmatafonov** [comment]
Привет

Котировки по REST не очень практично - они идут по вебсокетам, по подписке.
Выставление приказа в REST есть.

Вот тут куча примеров, готовые либы под php и питон
https://tradernet.ru/tradernet-api/auth-login
