### ISSUE TITLE
API for Silver Surfer

### ISSUE THREAD

**Issue by baio** [tradernet/tn.api#4]
Is it possible to add api for silver surefr ?

**Comment by Dmatafonov** [comment]
да, но надо много допиливать
сейчас его сигналы вообще в другой базе лежат

**Comment by baio** [comment]
Можно хотя бы приблезительно срок узнать ? месяц два три ?

**Comment by baio** [comment]
А можно как компромисное / верменое, решение добавить к HTML странице http://www.nettrader.ru/tradersclub/silversurfer , для каждой строки в таг или аттрибут код бумаги, я так понимаю при генерации эти данные все равно есть просто щас не рендерется

**Comment by Dmatafonov** [comment]
> при генерации эти данные все равно есть просто щас не рендерется

неа, нету

сайт nettrader.ru это простой cms на друпале - там даже бд ценных бумаг нет

сейчас откроем для публичного доступа один из портфелей SS, можно будет по api подписаться на его сделки в реальном времени

**Comment by baio** [comment]
ok

**Comment by baio** [comment]
так открыли в итоге портфель для паблика ?

**Comment by Dmatafonov** [comment]
Так точно!

https://tradernet.ru/user/Silver.Surfer.ru

**Comment by baio** [comment]
ккомбо, :zap:

спасибо

**Comment by baio** [comment]
Чтото не могу найти API для подписки на чужой портфель
