### ISSUE TITLE
Более подробная документация

### ISSUE THREAD

**Issue by baio** [tradernet/tn.api#6]
Не понятно когда исполняется приказ.

Могу ли я узнать при помощи АПИ что приказ исполнен.

Такж ене все структуры событий (например сообщение о приказе) имеют полное описание.

Также для описания структуры портфолио есть непонятные поля
и хотелось бы иметь перечегнь знчений для 
    securityType (t) и 
    securityKind (k)

``` TypeScript
export interface ITraderNetPosition {
    ///Тикер бумаги
    security: trader.TicketCodes
    ///Тип бумаги ???
    securityType: number
    ///Вид бумаги ???
    securityKind: number
    //Стоимость
    price: number
    ///Количество
    quantity: number
    ///Валюта
    currency: trader.CurrencyCodes
    ///Курс валюты
    currencyRate: number
    ///Наименование бумаги
    securityName: string 
    ///Альтернативное наименование бумаги
    securityName2: string  
    ///Цена открытия
    openPrice : number
    ///Рыночная цена
    marketPrice: number
    /*
    //???
    vm: string
    //???
    go: number
    //???
    profit_close: number
    //???
    acc_pos_id: number
    //???
    trade: Array<{}>
    */
}
```

**Comment by tradernet** [comment]
Добрый день!

Статусы приказов приходят по подписке: команда notifyOrders, событие orders, поле stat, последовательно принимает следующие значения:

1 Received (New) Получен

2 Cancel Req Запрос на отмену

10 Placed Размещён

11 Sent посланный

12 Partial Fill Частично заполнен

13 Cancel Sent Отменить Отправленные

20 Partial Executed Частично выполнен

21 Executed Выполнен

30 Partial Canceled 

31 Cancelled Отменён

70 Rejected Отказ

71 Expired Срок действия истёк

72 Partial Expired Срок действия истёк (частично выполнен)

73 Market Place Error 

74 Send Error 

75 Cancel Error

Свойства портфеля t и k.

t, тип бумаги, принимает одно из следующих значений:

1 Stock Акция Stock

2 Bond Облигация Bond

3 Futures Фьючерсы Futures

4 Option Опционы Option

5 Indexes Индексы Indexes

6 Money Деньги Money

7 Night Ночные торги NightTrade

k, подтип бумаги:

1 Common Обыкновенные

2 Pref Привилегированные

3 Percent Процентные

4 Discount Дисконтные

5 Delivery Поставочный

6 Rated Расчетный

7 Interval Интервальный

8 Crypto Криптовалюта

**Comment by baio** [comment]
nice, а нет возможности подписаться на оповещение об изменинии статусов приказа только раз и всегда получать изменения для ордеров, как это реализовано для стаканов.
